import type { Metadata } from "next";
import "./scss/globals.scss";

export const metadata: Metadata = {
  title: "QR Code Component using NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
          <link
            rel="icon"
            type="image/ico"
            href="./favicon.ico"
          />
        </head>
      <body>{children}</body>
    </html>
  );
}
